services:
  redis-1:
    image: redis:7.0-alpine
    container_name: redis-1
    ports:
      - "6379:6379"
    volumes:
      - /dockerVol/dell/Desktop/redis:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

